# common fragment
x-amd64: &amd64
  platform: linux/amd64

x-app: &app
  working_dir: /app

x-attachable: &attachable
  tty: true
  stdin_open: true

# app fragment
x-app-ports: &app-ports
  - 4321:4321

x-app-volumes: &app-volumes
  - ./:/app
  - node_modules:/app/node_modules

# computing component
services:
  app:
    <<: [*amd64, *app, *attachable]
    image: node:20.18.0-alpine
    command: npm run dev -- --host 0.0.0.0
    ports: *app-ports
    volumes: *app-volumes

# persistent data store
volumes:
  node_modules:
